# Generated by Django 3.0.5 on 2021-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
