# Generated by Django 3.0.5 on 2021-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210815_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='imag',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
