# Generated by Django 3.0.5 on 2021-08-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('names', models.CharField(max_length=200)),
                ('faceAdmin', models.ImageField(upload_to='')),
            ],
        ),
    ]
